---
language: c
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - libssl-dev
            - libgnutls28-dev
            - libnghttp2-dev
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - cmake
            - libuv
            - ldns
            - nghttp2
            - openssl

before_script:
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then sh ci/install-libuv.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then sh ci/install-ldns.sh; fi

script:
  - mkdir build && cd build && cmake ..
  - make all tests
  - ./tests
