---
language: c
dist: xenial

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - libssl-dev
            - libgnutls-dev
            - openssl
    - os: osx
      addons:
        homebrew:
          update: true
          packages:
            - cmake
            - libuv
            - ldns
            - openssl

before_script:
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then sh ci/install-libuv.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then sh ci/install-ldns.sh; fi
  - sh ci/install-quicly.sh

script:
  - ln -s /tmp/quicly 3rd/
  - mkdir build && cd build && cmake ..
  - make all tests
  - ./tests
  - mkdir quic-build && cd quic-build && cmake -DQUIC_ENABLE=ON ..
  - make all tests
  - ./tests
