---
language: c
dist: bionic

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake
            - libssl-dev
            - libgnutls28-dev
            - libnghttp2-dev
            - openssl
#    - os: osx
#      addons:
#        homebrew:
#          update: true
#          packages:
#            - cmake
#            - libuv
#            - ldns
#            - nghttp2
#            - openssl

before_script:
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then sh ci/install-libuv.sh; fi
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then sh ci/install-ldns.sh; fi
  - sh ci/install-quicly.sh

script:
  - ln -s /tmp/quicly 3rd/
  - mkdir build && cd build && cmake ..
  - make all tests
  - ./tests
  - cd ..
  - mkdir quic-build && cd quic-build
  - if [ "${TRAVIS_OS_NAME}" = linux ]; then cmake -DQUIC_ENABLE=ON ..; fi
  - if [ "${TRAVIS_OS_NAME}" = osx ]; then PKG_CONFIG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig cmake -DQUIC_ENABLE=ON ..; fi
  - make all tests
  - ./tests
